
    <meta charset="utf-8" />
    <meta name="description" content="<@= meta.description || meta.title @>" />
    <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700|Open+Sans:300italic,400,300,700'
        rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Julius+Sans+One' rel='stylesheet' type='text/css'>
    <link href="@~images/favicon.ico" rel="shortcut icon" />

    <@ renderStyles() @>
