  
                    <a class="item" href="https://embedthis.com/">Embedthis</a>
                    <a class="item" href="https://embedthis.com/expansive/">Expansive Site</a>
                    <a class="item" href="http://goo.gl/dGRDl4">Expansive News</a>
                    <a class="item" href="https://github.com/embedthis/expansive">Repository</a>
                    <a class="item" href="https://embedthis.com/blog/">Blog</a>
                    <a class="item" href="https://twitter.com/mobstream">Twitter</a>
