
                    <a class="item" href="https://www.embedthis.com/">Embedthis</a>
                    <a class="item" href="https://www.embedthis.com/expansive/">Expansive Site</a>
                    <span class="desktop-only">
                        <a class="item" href="https://www.embedthis.com/blog/categories/Expansive/">Expansive News</a>
                        <a class="item" href="https://github.com/embedthis/expansive">Repository</a>
                        <a class="item" href="https://www.embedthis.com/blog/">Blog</a>
                        <a class="item" href="https://twitter.com/embedthat">Twitter</a>
                    </span>
