.TH ME "1" "January 2014" "exp" "User Commands"
.SH NAME
exp \- Expansive -- Static web site generator
.SH SYNOPSIS
.B me 
    \fB--chdir dir\fR
    \fB--keep\fR
    \fB--nowatch\fR
    \fB--quiet\fR
    \fB--verbose\fR
    \fB--version\fR
.SH ""
.B Commands:
    exp generate
    exp run
    exp watch
    exp [path]
.SH DESCRIPTION

.PP
.SH "REPORTING BUGS"
Report bugs to dev@embedthis.com.
.SH COPYRIGHT
Copyright \(co 2004-2014 Embedthis Software. Embedthis Expansive is a trademarks of Embedthis Software.
.br
.SH "SEE ALSO"
pak
