/*
   exp.template.slots.h -- Native property slot definitions for the "exp.template" module
  
   This file is generated by ejsmod
  
   Slot definitions. Version 2.5.0.
 */

#ifndef _h_SLOTS_ExpTemplateSlots
#define _h_SLOTS_ExpTemplateSlots 1


/*
   Slots for the "exp.template" module 
 */

/*
   Prototype (instance) slots for "global" type 
 */


/*
    Class property slots for the "ExpParser" type 
 */
#define ES_ExpParser_NUM_CLASS_PROP                                    0

/*
   Prototype (instance) slots for "ExpParser" type 
 */
#define ES_ExpParser_parse                                             0
#define ES_ExpParser_NUM_INSTANCE_PROP                                 1
#define ES_ExpParser_NUM_INHERITED_PROP                                0

#define _ES_CHECKSUM_exp_template   5254

PUBLIC int expConfigureTemplateType(Ejs *ejs);
#endif
